# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Maciek/Documents/uklady_programowalne/ipintegrator/ipintegrator.srcs/sources_1/bd/modsystem/ip/modsystem_xbip_dsp48_macro_0_0/modsystem_xbip_dsp48_macro_0_0.xci
# IP: The module: 'modsystem_xbip_dsp48_macro_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Maciek/Documents/uklady_programowalne/ipintegrator/ipintegrator.gen/sources_1/bd/modsystem/ip/modsystem_xbip_dsp48_macro_0_0/modsystem_xbip_dsp48_macro_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'modsystem_xbip_dsp48_macro_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Maciek/Documents/uklady_programowalne/ipintegrator/ipintegrator.srcs/sources_1/bd/modsystem/ip/modsystem_xbip_dsp48_macro_0_0/modsystem_xbip_dsp48_macro_0_0.xci
# IP: The module: 'modsystem_xbip_dsp48_macro_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Maciek/Documents/uklady_programowalne/ipintegrator/ipintegrator.gen/sources_1/bd/modsystem/ip/modsystem_xbip_dsp48_macro_0_0/modsystem_xbip_dsp48_macro_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'modsystem_xbip_dsp48_macro_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
